# minimal Python image for reduced size
FROM python:3.9-alpine

WORKDIR /app

# Install necessary packages and clean up afterward
RUN apk add --no-cache libffi-dev openssl-dev && \
    apk add --no-cache --virtual .build-deps gcc musl-dev && \
    pip install --no-cache-dir requests && \
    apk del .build-deps

COPY test_nginx.py /app/test_nginx.py

# Add and switch to a non-root
RUN adduser -D pyuser
USER pyuser

# Run the script
CMD ["python", "test_nginx.py"]
