FROM python:3.9-slim
RUN adduser --disabled-password --gecos '' pyuser
USER pyuser

RUN pip install --no-cache-dir requests
COPY test_nginx.py /app/test_nginx.py
WORKDIR /app
CMD ["python", "test_nginx.py"]
